name: Notify on New Issue

on:
  issues:
    types: [opened]

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Telegram
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: ${{ secrets.bot_token }}
          chat_id: -1002295019134
          topic_id : 8